version: '2'
services:
    web:
        container_name: odoo_web
        build:
            context: .
            dockerfile: Dockerfile-odoo
        image: odoo-nginx:1.0
        depends_on:
            - db
        volumes:
            - odoo-web-data:/var/lib/odoo
        ports:
            - "8069:8069"
    db:
        container_name: odoo_db
        image: postgres:9.4
        environment:
            - POSTGRES_PASSWORD=odoo
            - POSTGRES_USER=odoo
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - odoo-db-data:/var/lib/postgresql/data/pgdata
    proxy:
        depends_on:
            - web
        container_name: odoo_proxy
        build:
            context: .
            dockerfile: Dockerfile-nginx
        image: proxy-nginx:1.0
        ports:
            - "80:80"
            - "443:443"
volumes:
    odoo-web-data:
    odoo-db-data:
